from .created import Created
from .duplicates import Duplicates
from .exif import Exif
from .extension import Extension
from .filename import Filename
from .filesize import FileSize
from .last_modified import LastModified
from .python import Python
from .regex import Regex
